services:
  backend:
    build: ./backend
    container_name: django-backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=chartapi.settings
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
